// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changePhone_in_Client : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changePhone_in_Client));
        
        string IMigrationMetadata.Id
        {
            get { return "202101232205491_changePhone_in_Client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
